// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var arrayEquality, compareDigits, five, four, result, six, three, two;
    arrayEquality = function(arr1, arr2) {
      var i, len, _i;
      len = arr1.length;
      if (len !== arr2.length) {
        return false;
      }
      for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
        if (arr1[i] !== arr2[i]) {
          return false;
        }
      }
      return true;
    };
    compareDigits = function(num1, num2) {
      var arr1, arr2, i, len, str1, str2, _i;
      str1 = num1.toString();
      str2 = num2.toString();
      len = str1.length;
      arr1 = [];
      arr2 = [];
      for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
        arr1.push(parseInt(str1[i], 10));
        arr2.push(parseInt(str2[i], 10));
      }
      arr1.sort();
      arr2.sort();
      console.log(arr1);
      console.log(arr2);
      return arrayEquality(arr1, arr2);
    };
    result = 0;
    while (true) {
      result += 1;
      two = result * 2;
      three = result * 3;
      four = result * 4;
      five = result * 5;
      six = result * 6;
      if (six.toString().length === result.toString().length) {
        if (compareDigits(result, two)) {
          if (compareDigits(result, three)) {
            if (compareDigits(result, four)) {
              if (compareDigits(result, five)) {
                if (compareDigits(result, six)) {
                  break;
                }
              }
            }
          }
        }
      }
    }
    return $('#answer').text(result);
  });

}).call(this);
